[package]
name = "refraction"
version = "0.1.0"
edition = "2024"
authors = ["Rowan Preston <rowan.t.preston@gmail.com>"]
include = ["LICENSE", "Cargo.toml", "README.md", "src/*.rs"]

[dependencies]
eframe = "0.31"
egui = "0.31.1"